// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyWtvHGNQZ9yhvMGEpaRNSSDO13OYLUgY',
    appId: '1:511383017479:web:0b107aaea05e635d82f2a2',
    messagingSenderId: '511383017479',
    projectId: 'alu-internship-hub-24ac3',
    authDomain: 'alu-internship-hub-24ac3.firebaseapp.com',
    storageBucket: 'alu-internship-hub-24ac3.firebasestorage.app',
    measurementId: 'G-TD04LW5DNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgIGRdIXilrCx-3mHyvEJZMw5CYZ6JnFY',
    appId: '1:511383017479:android:663c26a43beb861382f2a2',
    messagingSenderId: '511383017479',
    projectId: 'alu-internship-hub-24ac3',
    storageBucket: 'alu-internship-hub-24ac3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK7NNtfvEQH7tVdUBIHR6sSeu56zm50S8',
    appId: '1:511383017479:ios:c1a6fbf2a70691c182f2a2',
    messagingSenderId: '511383017479',
    projectId: 'alu-internship-hub-24ac3',
    storageBucket: 'alu-internship-hub-24ac3.firebasestorage.app',
    iosBundleId: 'com.example.aluInternshipApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK7NNtfvEQH7tVdUBIHR6sSeu56zm50S8',
    appId: '1:511383017479:ios:c1a6fbf2a70691c182f2a2',
    messagingSenderId: '511383017479',
    projectId: 'alu-internship-hub-24ac3',
    storageBucket: 'alu-internship-hub-24ac3.firebasestorage.app',
    iosBundleId: 'com.example.aluInternshipApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyWtvHGNQZ9yhvMGEpaRNSSDO13OYLUgY',
    appId: '1:511383017479:web:bf8c574dd519e84182f2a2',
    messagingSenderId: '511383017479',
    projectId: 'alu-internship-hub-24ac3',
    authDomain: 'alu-internship-hub-24ac3.firebaseapp.com',
    storageBucket: 'alu-internship-hub-24ac3.firebasestorage.app',
    measurementId: 'G-S91CR6KFL6',
  );
}
